[package]
name = "p2pchat"
version = "0.1.0"
authors = ["kevin-koehler <kevin.koehler@usask.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
